name: Node.js CI

on:
  push:
    branches:
      - '**'
      - '!qa'
      - '!master'
  pull_request:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '14'

    - name: Install
      run: npm install

    - name: Test
      run: npm run test